AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  pt-chatbot

  Sample SAM Template for pt-chatbot

Globals:
  Function:
    Timeout: 30
    #Tags:
    Environment:
      Variables:
        ENV: dev

Resources:
  PTChatbotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pt-chatbot/
      Handler: app.lambda_handler
      Runtime: python3.9
      #Policies: "AmazonSESFullAccess"
      Architectures:
        - x86_64
      MemorySize: 128
      Environment:
        Variables:
          SENDER: "pt.chatbot.dev@danstormsconsulting.io"
          RECIPIENT: "pt.chatbot.dev@danstormsconsulting.io"
  PTChatbotEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pt-chatbot-email/
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies: "AmazonSESFullAccess"
      Architectures:
        - x86_64
      MemorySize: 128
      Environment:
        Variables:
          SENDER: "pt.chatbot.dev@danstormsconsulting.io"
          RECIPIENT: "pt.chatbot.dev@danstormsconsulting.io"
      # Events:
      #   HelloWorld:
      #     Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
      #     Properties:
      #       Path: /hello
      #       Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PTChatbotFunction:
    Description: "PT Chatbot Function Lambda Function ARN"
    Value: !GetAtt PTChatbotFunction.Arn
  PTChatbotEmailFunction:
    Description: "PT Chatbot Email Lambda Function ARN"
    Value: !GetAtt PTChatbotEmailFunction.Arn
  PTChatbotFunctionIamRole:
    Description: "Implicit IAM Role created for PT Chatbot Function function"
    Value: !GetAtt PTChatbotFunction.Arn
  PTChatbotEmailFunctionIamRole:
    Description: "Implicit IAM Role created for PT Chatbot Email Function function"
    Value: !GetAtt PTChatbotFunction.Arn
